services:
  app:
    build: .
    container_name: nodejs-express-app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.production    # RDS creds, SESSION_SECRET, etc.
    command: node src/app.js
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge
